db.driver=com.mysql.cj.jdbc.Driver
db.url=${DB_URL:jdbc:mysql://localhost:3306/ariza_takip_sistemi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
db.username=${DB_USERNAME:root}
db.password=${DB_PASSWORD:Sifre123!}
db.pool.initialSize=3
db.pool.minSize=3
db.pool.maxSize=10
db.pool.maxIdleTime=300

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=${HIBERNATE_SHOW_SQL:true}
hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
hibernate.hbm2ddl.auto=${HIBERNATE_HBM2DDL_AUTO:update}

# Mail Settings (Gmail example)
mail.host=smtp.gmail.com
mail.port=587
mail.username=fase2507@gmail.com
mail.password=xebevbjcnxsxgqxz
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.from=fase2507@gmail.com

# Gemini Settings
gemini.api.key=HIDDEN
gemini.model=gemini-2.0-flash
gemini.url=https://generativelanguage.googleapis.com/v1beta/models
